version: '3.9'

services:
  database:
    image: postgres
    container_name: CRUDSogni
    restart: always
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'dev123'
      POSTGRES_DB: 'database'
    volumes:
     - mydb:/var/lib/postgresql/data


volumes:
    mydb:
      driver: local